services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15

  postgres:
    image: bitnamilegacy/postgresql:17.6.0-debian-12-r4
#    command: postgres -c synchronous_commit=off
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: db
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replicator
      POSTGRESQL_REPLICATION_PASSWORD: replicator_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 15

  postgres-replica:
    image: bitnamilegacy/postgresql:17.6.0-debian-12-r4
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replicator
      POSTGRESQL_REPLICATION_PASSWORD: replicator_pw
      POSTGRESQL_MASTER_HOST: postgres
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      POSTGRESQL_PASSWORD: root
    ports:
      - "5433:5432"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgdata-replica:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 15

  app:
    build: .
    environment:
      ENV: local
      HTTP_PORT: "8080"
      LOG_LEVEL: debug
      DATABASE_URL: postgresql://postgres:root@postgres:5432/db?sslmode=disable
      DATABASE_REPLICA_URL: postgresql://postgres:root@postgres-replica:5432/db?sslmode=disable
      PG_POOL_MAX_CONNS: "100"
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
      - "6060:6060"
    depends_on:
      postgres:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:11.4.0
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
  pgdata-replica:
